<div class="footer-bottom">
<?=
            $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer_bottom')
            ->toHtml();

        ?>
</div>
<div class="footer-bottom-mobile">
<?=
            $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer_bottom_moblie')
            ->toHtml();

        ?>
</div>