<div class="description">
    <div class="description__top">
        <h3>Amafli 5 Seater Aluminium Outdoor Modular Lounge Setting Featuring Sunbrella Fabric</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
            ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
            nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit
            anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque
            laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae
            dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia
            consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem
            ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut
            labore et dolore magnam aliquam quaerat voluptatem.</p>
    </div>
    <div class="description__content">
        <div class="description__content__block">
            <div class="block-img"></div>
            <div class="block-content">
                <h4>Luna Stone Collection</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip.
                </p>
                <p><a href="#"><span>Read more</span></a></p>
            </div>
        </div>
        <div class="description__content__block">
            <div class="block-img"></div>
            <div class="block-content">
                <h4>Luna Stone Dining Table</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip.
                </p>
                <p><a href="#"><span>Read more</span></a></p>
            </div>
        </div>
        <div class="description__content__block">
            <div class="block-img"></div>
            <div class="block-content">
                <h4>Summerset Dining Chair</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip.
                </p>
                <p><a href="#"><span>Read more</span></a></p>
            </div>
        </div>
    </div>
</div>